name: myenv  

channels:
  - defaults
  - conda-forge  

dependencies:
  - python=3.10 
  - pip
  - colorama==0.4.6
  - contourpy==1.3.0
  - cycler==0.12.1
  - fonttools==4.54.1
  - imageio==2.35.1
  - iniconfig==2.1.0
  - Jinja2==3.1.6
  - kiwisolver==1.4.7
  - lazy_loader==0.4
  - MarkupSafe==3.0.2
  - matplotlib==3.9.2
  - mpmath==1.3.0
  - networkx==3.3
  - numpy==2.1.1
  - opencv-contrib-python==4.10.0.84
  - packaging==24.1
  - pandas==2.2.3
  - pillow==10.4.0
  - pluggy==1.5.0
  - pygame==2.6.1
  - pyparsing==3.1.4
  - pytest==8.3.5
  - pytest-html==4.1.1
  - pytest-metadata==3.1.1
  - python-dateutil==2.9.0.post0
  - pytz==2024.2
  - scikit-image==0.24.0
  - scipy==1.14.1
  - seaborn==0.13.2
  - six==1.16.0
  - sympy==1.13.2
  - tifffile==2024.9.20
  - tzdata==2024.2

  - pip:
    - pytest-html==4.1.1  
