name: Python CI with Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 flake8-html pytest pytest-html

      - name: Lint with flake8 and generate report
        run: |
          mkdir -p reports/lint
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run tests and generate report
        run: |
          mkdir -p reports/tests
          pytest --html=reports/tests/report.html --self-contained-html

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: reports/lint

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/tests
